/**
 * Example Usage - How to use the GitHub App & OpenAI Integration
 * 
 * Run with: node scripts/example-usage.js
 */

require('dotenv').config();
const {
  readFile,
  writeFile,
  getChatGPTResponse,
  listFiles,
  createPullRequest,
} = require('../openai-github-integration');

async function main() {
  try {
    console.log('🎯 Starting Example Usage\n');

    // Example 1: List all files in the repository
    console.log('📂 Example 1: Listing repository files');
    console.log('─'.repeat(50));
    const files = await listFiles('');
    console.log(`Found ${files.length} items:`);
    files.forEach(f => {
      console.log(`  ${f.type === 'dir' ? '📁' : '📄'} ${f.name}`);
    });
    console.log();

    // Example 2: Read a file
    console.log('📖 Example 2: Reading a file');
    console.log('─'.repeat(50));
    try {
      // Try to read README if it exists, otherwise try index.html
      let content;
      try {
        content = await readFile('README.md');
      } catch (e) {
        console.log('README.md not found, trying index.html...');
        content = await readFile('index.html');
      }
      console.log(`Content preview (first 500 chars):\n${content.substring(0, 500)}...`);
    } catch (e) {
      console.log('⚠️  Could not read files:', e.message);
    }
    console.log();

    // Example 3: Ask ChatGPT for analysis
    console.log('🤖 Example 3: Getting ChatGPT analysis');
    console.log('─'.repeat(50));
    const analysis = await getChatGPTResponse(
      'Please analyze this code and suggest improvements for code quality and performance.',
      'This is a test prompt. In production, you would pass actual file content here.'
    );
    console.log('ChatGPT Response:');
    console.log(analysis);
    console.log();

    // Example 4: Generate and write a new file
    console.log('✍️  Example 4: Creating a new file via ChatGPT');
    console.log('─'.repeat(50));
    const generatedContent = `<!-- Generated by ChatGPT on ${new Date().toISOString()} -->
<section class="ai-generated">
  <h2>AI-Generated Content</h2>
  <p>This section was generated by integrating OpenAI ChatGPT with GitHub App.</p>
  <p>The integration allows automatic code generation, analysis, and updates.</p>
</section>`;

    // Uncomment to actually write the file
    // await writeFile(
    //   'generated-content.html',
    //   generatedContent,
    //   'feat: Add AI-generated content section'
    // );
    console.log('Generated content (not written):\n', generatedContent);
    console.log();

    console.log('✅ Example usage completed successfully!\n');
    console.log('💡 Tips:');
    console.log('  - Uncomment the writeFile() call to actually create files');
    console.log('  - Use readFile() to get content for ChatGPT analysis');
    console.log('  - Chain operations: read → analyze → write → create PR');
    console.log('  - Check GITHUB_APP_SETUP.md for more examples');

  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

main();
